server:
  port: 8989
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 10000MB #最大请求文件的大小
      max-file-size: 10000MB
      file-size-threshold: 20MB
  thymeleaf:
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 127.0.0.1
    port: 6379
upload:
  # 上传文件路径 示例（ Windows配置C:/wwwroot/video/，Linux配置 /video/upload/）
  path: C:/wwwroot/video/
  url-domain: http://vv.zhiyunxy.com/videos
